version: "3.3"

services:
  api:
    build: .
    container_name: backend-api
    restart: unless-stopped
    networks:
      - c

  reverseProxy:
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - api
    networks:
      - backend-api-network

networks:
  backend-api-network:
    driver: bridge
